### ISSUE TITLE
How to ignore items in destination collection based on condition?

### ISSUE THREAD

**Issue by Deilan** [AutoMapper/AutoMapper.Collection#107]
Is there a way to ignore some items in a destination collection based on some condition?

**Comment by TylerCarlson1** [comment]
Currently no.
AutoMapper doesn't have conditions for Collections and neither does AutoMapper.Collections.

**Comment by Deilan** [comment]
@TylerCarlson1 May I request such a feature? Should I fill an issue at [AutoMapper/AutoMapper](https://github.com/AutoMapper/AutoMapper) repo for that?

**Comment by TylerCarlson1** [comment]
I don't see the benefit of doing conditionally ignoring items.  The main use of this is re-using existing lists for things like EntityFramework which doesn't like re-generating lists like AutoMapper does.

I'm curious what is your scenario where you would need to ignore some items in a list while altering the others.

Also from what you are asking it seems more like an AM.Collections request than an AutoMapper one.

**Comment by TylerCarlson1** [comment]
So it sounds instead of just Add/Map/Remove you want to add Ignore when mapping two collections to each other.

I'm still not understanding how this can be applied to Entity Framework because if you map a parent/child relationship you'll get the entire list in which case it would update everything.  If you are talking about no changes ignoring the map, what AutoMapper will do is map to existing item, but since there's no change, EntityFramework won't send and update queries back to the SQL server.  So if you load everything, change nothing, and save, then nothing will be updated in SQL.

You might have to elaborate or give a gist example so I can see what exactly you want to do.
Or if you can make a PR for it.

**Comment by superman-lopez** [comment]
This is an old request but I have the same requirement.

In my application layer (server side application enforcing business rules, as well as client application) all changes are made in DTO/Resources, and then are mapped directly to EF Core entities.  As such, all changes on entities are only made through AutoMapper and AutoMapper.Collection.

There is one business rule that I would like to implement on the entities, and so I was hoping to implement this in the Mapping Profile.  In my [gist](https://gist.github.com/superman-lopez/10d4a80ba7690554369a1d9e6041d67c) you can see I have a boolean for the instance to be read only.  The setting of the read only property is allowed to be done through the DTO.  But once set, all properties on the entity are no longer allowed to be changed (including `ReadOnly`).

If I could I could ignore the item conditionally, it would make it such that the mapping will include all items in the collection and update the whole collection except those where the `ObjectEntity.ReadOnly` is set to `true`.  So in my gist, when I call `objects = mapper.Map<List<ObjectDto>, List<ObjectEntity>>(dtoObjects, objects);` `objects` will include all mapped updated instances, plus the original objects that were not ignored in the mapping due to `ReadOnly` setting to `true`.

**Comment by Tasteful** [comment]
An little other approach is to modify the tracked entitles in the change tracker directly. 

Before you call the `SaveChanges`-method, can use look at the objects in EF ChangeTracking and make appropriate changes/revert etc. You find the change tracking with the entities for EFCore on the `dbContext.ChangeTracker.Entries()`. You have then the full possibility to raise events for the changed entities or change the state to remove the entity instead of update etc.

**Comment by superman-lopez** [comment]
Thanks I think that's a good approach to consider!

**Comment by chipic** [comment]
> So it sounds instead of just Add/Map/Remove you want to add Ignore when mapping two collections to each other.
> 
> I'm still not understanding how this can be applied to Entity Framework because if you map a parent/child relationship you'll get the entire list in which case it would update everything. If you are talking about no changes ignoring the map, what AutoMapper will do is map to existing item, but since there's no change, EntityFramework won't send and update queries back to the SQL server. So if you load everything, change nothing, and save, then nothing will be updated in SQL.
> 
> You might have to elaborate or give a gist example so I can see what exactly you want to do.
> Or if you can make a PR for it.

For example, you have the collection of Users. One of the Users is an Admin. You read the collection from EF, you modify it (add new Users, remove existing one, update some info for the others). Now you need to map it all to EF model, EqualityComparison((source, dest) => source.Id == dest.Id) is used .  Let's say there is a requirement - Admin should be immutable. The array that you try to map to EF arrya doesn't contain an Admin entity, only ordinary Users are there. When you map such array, Admin entity will be removed from EF array, the entity will be removed from a DB. So, in this case, we need a way to ignore a certain item in a destination collection, so it is not updated or removed.

**Comment by Tasteful** [comment]
@chipic you can change the state on the tracked entities to make them NotModified/Untracked to EF, then no update will be excecuted down to the database.

Otherwise a generic source/destination filter is hard to build in a intuitive way because it can be hard to understand if the items will be keept or ignored in the destination.
