### ISSUE TITLE
dto's fields are different from entity,

### ISSUE THREAD

**Issue by FenglinDeng** [AutoMapper/AutoMapper.Collection#111]
Hi, Mr Carlson, I'm using AutoMapper.Collection to update dto to entity,but some of dto's fields name are not as same as entity,what happens is an exception at the "Mapper.AssertConfigurationIsValid();".

this is my entity:
```
public class Book
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public int Year { get; set; }
        public decimal Price { get; set; }
        public string Genre { get; set; }

        // Foreign Key
        public int AuthorId { get; set; }
        // Navigation property
        public Author Author { get; set; }
    }
```

And these are dto and AutoMapper configuration:
```
    public class TestBookDto
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
    }

    public class BookProfile : Profile
    {
        public BookProfile()
        {
            CreateMap<TestBookDto, Book>()
                .EqualityComparison((bdto, b) => bdto.BookId == b.Id)
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.BookId));
        }
    }
```
```
        public static void InitAutoMapper()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.AddCollectionMappers();
                cfg.SetGeneratePropertyMaps<GenerateEntityFrameworkPrimaryKeyPropertyMaps<BookServiceContext>>();

                cfg.AddProfile<BookProfile>();
            });

            Mapper.AssertConfigurationIsValid();
        }
``` 
there is no error in compiling,but an exception occured when it is being executed.  did I make any mistakes ?

**Comment by TylerCarlson1** [comment]
`AssetConfigurationIsValid()` is AutoMapper feature not AM.Collections.  What this does is check your mapping and see if anything wasn't mapped.  It isn't required to run the application, it's just there to catch possible miss-configurations in your mappings.
Issue is AuthorId and Author aren't mapped.  What you have to do is ignore members or explicitly ignore them in order for `AssetConfigurationIsValid()` to not throw an exception.

Also `.EqualityComparison((bdto, b) => bdto.BookId == b.Id)` isn't needed because you have `cfg.SetGeneratePropertyMaps<GenerateEntityFrameworkPrimaryKeyPropertyMaps<BookServiceContext>>();` which will see `Id` is part of the primary key and is mapped to `BookId` and generate the equality comparison for you.
