### ISSUE TITLE
Why do we need ObjectToEquivalencyExpressionByEquivalencyExistingMapper as well

### ISSUE THREAD

**Issue by rizi** [AutoMapper/AutoMapper.Collection#27]
Hi, I just checked your code and I really like it, I just don't understand why you need the "second" mapper (ObjectToEquivalencyExpressionByEquivalencyExistingMapper), 
can you enlighten me? Thx for the great extension, it's really useful!!

**Comment by TylerCarlson1** [comment]
It is mostly used for Persist in AM.Collections.EF and AM.Collections.LinqToSQL.  What it does is take an object and convert it into an expression that can be used to find its matched object in the database.

So if you need to insert or update you need to know what it is matching on Id or multiple Ids.  If you have code
```
Mapper.Initialize(cfg => 
{
  cfg.AddProfile<CollectionProfile>();
  cfg.CreateMap<Entity,Dto>().EqualityComparison((e, d) => e.Id == d.Id);
}
```
you can make a map like this
```
var dto = new Dto {Id = 5};
var findMatchExpression = Mapper.Map<Dto, Expression<Func<Entity,bool>>>(dto); // Returns e => e.Id == 5;
var match = db.Entities.FirstOrDefault(findMatchExpression); // Match will be null or Dto that has an Id of 5
```

From there you can use the match to insert or update the Entity object.  Instead of having to do
```
var dto = new Dto {Id = 5};
var match = db.Entities.FirstOrDefault(e => e.Id == dto.Id);
```

Or you can just use
```
var dto = new Dto {Id = 5};
db.Entities.Persist().InsertOrUpdate<Dto>(dto); // Insert or Update
db.Entities.Persist().Remove<Dto>(dto); // Delete
// call db.SubmitChanges() to commit
```

If you aren't using this for ORM's to map back to the database, you don't really get any use out of this.
When I made this I made it to be compatible with updating EF/LinqToSQL with as little code as possible.

**Comment by TylerCarlson1** [comment]
Not sure you know but AutoMapper has the functionality to map expressions now. https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)

And UseAsDataSource is like Persist where it does all those mappings behind the scenes.

**Comment by rizi** [comment]
I know that AutoMapper supports Expression mapping because I was the first one who make this work and later on Jimmy added it to AutoMapper and also improved it.
Br
