### ISSUE TITLE
How to avoid static EquivilentExpression.GenerateEquality.Add call in order to work with a container

### ISSUE THREAD

**Issue by maurosampietro** [AutoMapper/AutoMapper.Collection#28]
I'm using Automapper with a container.
I have just added Automapper.Collection.

Adding the following line to the configuration
`EquivilentExpressions.GenerateEquality.Add( new GenerateEntityFrameworkPrimaryKeyEquivilentExpressions<MyContext>() );
`   
Leads to the following exception:

"Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance."

How can i avoid the static call to EquivilentExpression.GenerateEquality.Add?

**Comment by TylerCarlson1** [comment]
If you have an instance of IMapper then pass that instance into the EF primary key generator constructor.  If you don't it will use the static instance by default. It's not the add function that throws the exception.

Sent from my iPhone

On Jan 12, 2017, at 2:53 AM, maurosampietro <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm using Automapper with a container.
I have just added Automapper.Collection.

Adding the following line to the configuration
EquivilentExpressions.GenerateEquality.Add( new GenerateEntityFrameworkPrimaryKeyEquivilentExpressions<MyContext>() );
Leads to the following exception:

"Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance."

How can i avoid the static call to EquivilentExpression.GenerateEquality.Add?

-

**Comment by maurosampietro** [comment]
That was the solution. Thank you
