### ISSUE TITLE
Attempting to use this with EF 6

### ISSUE THREAD

**Issue by foobarred1** [AutoMapper/AutoMapper.Collection#30]
Testing the Automapper.Collection with EF6 the ability to remove objects from a collection.

Let's say that the collection started with a record, and I'm mapping an empty collection (count=0) to the EF collection.  It seems to map properly, but when I go to save it, I get the following error:

An unhandled exception of type 'System.InvalidOperationException' occurred in EntityFramework.dll

Additional information: The operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted.

This is my code:
```
Imports AutoMapper
Imports AutoMapper.Mappers
Imports AutoMapper.Collection
Imports AutoMapper.EntityFramework
Imports AutoMapper.EquivilencyExpression

Public Class QuoteModel
    Public Property ID As Integer
    Public Property Quote_Lines As List(Of Quote_LinesDTO)
    Public Sub New()
        Me.Quote_Lines = New List(Of Quote_LinesDTO)
    End Sub
End Class
Public Class Quote_LinesDTO
    Public Property ID As Integer
    Public Property Line_ID As Integer
    Public Property Date_Created As DateTime
    Public Property User_Created_ID As Guid
    Public Property GlobalID As Guid

End Class

Public Class Form1

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Using theContext As New FleetFusionEntities1
            Dim theQuote As Quote = theContext.Quotes.Where(Function(ent) ent.ID = 151709).SingleOrDefault
            Dim theQuoteModel As New QuoteModel
            theQuoteModel.ID = 151709

            'theQuoteModel.Quote_Lines.Add(New Quote_LinesDTO With {.ID = 5, .Line_ID = 2, .Date_Created = Now, .GlobalID = Guid.NewGuid, .User_Created_ID = Guid.NewGuid})


            Dim MapConfig As New AutoMapper.MapperConfiguration(Sub(cfg) cfg.AddProfile(Of Automapper_Profile)())
            Dim Mapper As AutoMapper.IMapper = New AutoMapper.Mapper(MapConfig)

            Mapper.Map(theQuoteModel, theQuote)
            theContext.SaveChanges()
        End Using
    End Sub
End Class

Public Class Automapper_Profile
    Inherits AutoMapper.Mappers.CollectionProfile
    Public Sub New()
        CreateMap(Of QuoteModel, Quote)()
        CreateMap(Of Quote_LinesDTO, Quote_Lines).EqualityComparision(Function(dto, ent) dto.ID = ent.ID)

        'CreateMap(Of Quote_Lines, Quote_Lines).EqualityComparision(Function(dto, ent) dto.ID = ent.ID) _
        '    .ForMember(Function(ent) ent.Quote, Sub(opts) opts.Ignore()) _
        '    .ForMember(Function(ent) ent.Quote_ID, Sub(opts) opts.Ignore())

    End Sub
End Class`

```

**Comment by TylerCarlson1** [comment]
The issue is when you remove the objects from the Quote_Lines collection in EF they get orphaned instead of deleted and this is where exception shows because it can null the Foreign Key to orphan the object.

Issue is better explained here http://stackoverflow.com/questions/11033348/is-it-possible-to-remove-child-from-collection-and-resolve-issues-on-savechanges

To fix said example you would need to make ID and Line_ID a composite key in Quote_Lines EF object.  Currently it's most likely just the ID and that's why it's being orphaned.
Other workaround with delete orphans solution as explained in #4.

**Comment by foobarred1** [comment]
I went ahead and copied the code for DeleteOrphans<T> in #4, and it works!  Any chance you'll be incorporating this code soon?

Thanks.

**Comment by TylerCarlson1** [comment]
Don't think so right now.  I think that you should do it the proper way so that EF deletes instead of orphaning children.  If you can't do that for whatever reason you have to add extra code for the workaround.

**Comment by foobarred1** [comment]
If I understand what you mean is the "proper way", I'd rather not have to loop through each collection to find out what's missing and do a remove so that EF deletes them.

Is there a downside to using the DeleteOrphans code?

**Comment by TylerCarlson1** [comment]
No read the stack overflow article.  That's the proper way.  The proper way is making the items in the child collection have a composite primary key that includes the Foreign Key to the parten class.  If the Foreign Key is included in the Primary Key, then when you remove from the child collection it will delete the entry instead of trying to orphan it and get the exception.

If you do that you don't need to use DeleteOrphans or iterate through the collections.  Then EF would work more how you would think it would work.

**Comment by foobarred1** [comment]
I understand now.  Thanks for the link and explanation.
