### ISSUE TITLE
Add null check to avoid NRE

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper.Collection#71]
The included files in the report of #69 have a comment that `ExpressionExtentions.GetHashCodeExpression<>` should check for `null` to avoid `NullReferenceException` when `GetHashCode` is invoked.

Probably should be included in https://github.com/AutoMapper/AutoMapper.Collection/blob/58b519914adf6146403c8ff8a92dbdb0b5d53c50/src/AutoMapper.Collection/EquivalencyExpression/ExpressionExtentions.cs#L55

![image](https://user-images.githubusercontent.com/357589/34321214-d61d6d82-e809-11e7-8bd0-e3847018b412.png)

**Comment by TylerCarlson1** [comment]
Hmm I don't know.  I don't think this is a problem anywhere.  The real problem is when property maps are not null in the auto generated ones, but you don't use them.

**Comment by rizi** [comment]
@TylerCarlson1 I think it can be a problem because wenn encountered it in a real life application, where the key can be null. And If its null we get a null reference exception we can not handle because it happens in the GetHashcode call. I think its worth the check or at least dont call GetHashcode in that case( If its possible)

**Comment by TylerCarlson1** [comment]
Re-looking at this, what would be the best option?  Make expression list empty if anything is null, or make the hash code default to 0 in these null cases?  I would think it wouldn't have much impact because comparison will happen afterward to confirm they are equal even if they get grouped together.

Also brings up another point.  If both properties are null should they be equivalent to each other, or should they not be?

**Comment by rizi** [comment]
@TylerCarlson1 If a property is null I would use 0 for the hash code(r# is doing the same when generating equals/hashcode implementations).
If both properties are null --> hash code will be 0 -->  they are equivalent --> and then the comparison will decide. what do you think?

**Comment by Tasteful** [comment]
If the comparison expression is complex like 
```
(s, d) => s.Id == d.Id && x.Prop1 == d.Prop1
(s, d) => s.Id == d.Id
```
I think we can return `0` for the `GetHashCode()`, I think if all the source properties is `null` we should treat that as a new item and add a new row into the destination collection without try to find if that row already exists. Otherwise if 2 new items are added but all the key-properties is `null` the destination will only have one item.

**Comment by TylerCarlson1** [comment]
That should be fine making `GetHashCode()` equal `0` then if `null`.  I will double check on that making them separate HashSets, because I think if you add 2 or more with ID = 0 they both get added, so adding this null logic shouldn't make any difference.
