### ISSUE TITLE
Error handling with invalid DbContext

### ISSUE THREAD

**Issue by Baune8D** [AutoMapper/AutoMapper.Collection#82]
I recently had a problem that took ages to solve.

Refer to this issue for details:
https://github.com/AutoMapper/AutoMapper/issues/2612

Basically:
https://github.com/AutoMapper/AutoMapper.Collection/blob/master/src/AutoMapper.Collection.EntityFramework/GenerateEntityFrameworkPrimaryKeyPropertyMatches.cs#L24
```_context.ObjectContext``` throws an exception if DbContext is invalid.
In my case the default context constructor used a connection string which was invalid on all but my development machine.
This makes the function return empty property maps, so it looks like mapping fails because of missing maps.

It would be great to throw an exception stating that the context is invalid instead. Would have saved me days of bug hunting :)

**Comment by TylerCarlson1** [comment]
I don't think that would be a problem to re throw that exception up, but it has to be very specific what gets re thrown.  There are other exceptions that get called and are ignored because of things like there's no matching table in that object context, but could be matching in another object context you set up, and things like that.

PR is welcome.

**Comment by Tasteful** [comment]
@Baune8D I tried to reproduce this issue but without luck. Can you provide with an example (or test skeleton) on your mapping and the wrong connection string that will make it to fail?
