### ISSUE TITLE
Speculations on How Collections Get Mapped

### ISSUE THREAD

**Issue by markolbert** [AutoMapper/AutoMapper.Collection#85]
I ran into a situation involving collections and Automapper which I solved through a less-than-intuitive workaround. I've tried to describe the problem, and my solution, in the first answer to https://stackoverflow.com/questions/50382252/mapping-collections-in-automapper/50421075. 

If my speculations on how Automapper handles collections are correct, would it be possible to tweak the logic so it ignores differences in collection types between destination and source, as long as the destination collection type can accept an "add"?

I'd also be interested in correcting my theory, if something else is going on. Thanx!

**Comment by TylerCarlson1** [comment]
If you use UseDestinationValue for your map it should use the value set instead of trying to recreate it.

Also collections mappings only work if the classes inherit from ICollection not if they have Add function.
You have add in your validated collection but if it doesn't inherit from `ICollection<CommunityUserModel>` AutoMapper and by extension AutoMapper.Collections can't automatically map it the way you want.
